// @ts-check

// Fleet-save micro-fleet feature — ONE unified floating button that automates the
// "park the fleet on a moon, scatter micro-fleets to the planets, then
// pull everything back" workflow.
//
// # The unified button — two zones
//
// A single circular button split into two equal-height zones, stacked vertically:
//
//   - TOP (Send): from the current MOON, send a fixed micro-fleet
//     (Stacjonuj / mission=4) to each target defined for that moon in the routes
//     config, skipping targets that already have a deployment inbound. Ships are
//     preloaded via the fleetdispatch URL `am<shipId>=count` param, so the page
//     lands on fleet step 1 with the micro-fleet already selected. With no route
//     for the current body, a tap opens the dashboard's route-setup tab instead.
//   - BOTTOM (Collect): TAP sends EVERYTHING (all ships + all resources) from the
//     current planet back to the ad-hoc collect target. LONG-PRESS (300ms+) marks
//     the body you're standing on as that collect target. The label shows the
//     current target so it's clear where a collect run goes.
//
// # Two-tap send model (TOS-safe: one click → one originated request)
//
// On the fleetdispatch page each zone drives the game's own two-step
// form one tap at a time (the zone shows "Send", then "Next"/"Send"):
//   - first tap → (collect: select all ships) → click Continue,
//     wait for step 2.
//   - second tap → (collect: load all resources) → stash the post-send
//     redirect URL in `oge_fsRedirect` → click the native dispatch button.
// The only server-visible action a tap originates is the final dispatch.
//
// # Post-send redirect (asymmetric — see deployRedirect bridge)
//
//   - Micro: redirect to BARE fleetdispatch on the same moon. We do NOT
//     pre-pick the next target here, because the target we just sent to
//     is not yet in `#eventContent` — deferring the pick to the reloaded
//     page (where it IS) keeps "skip already-sent" correct.
//   - Collect: redirect to the next planet's fleetdispatch already aimed
//     at the collect target (we always advance PAST the current planet,
//     so the not-yet-visible current leg doesn't matter).
//
// @see ./pure.js — URL builders, target picking, the routes DSL.
// @see ./domHelpers.js — DOM readers + fleet-step drivers.
// @see ../../bridges/deployRedirect.js — consumes `oge_fsRedirect`.
// @see ../shared/draggableButton.js — drag + focus persistence.

import { settingsStore } from '../../state/settings.js';
import { parseUniverseId } from '../../lib/universeId.js';
import {
  fsRoutesStore,
  flushFsRoutesStore,
  stampFsRoutesChanged,
  FS_REDIRECT_KEY,
} from '../../state/fsRoutes.js';
import {
  installDrag,
  installFocusPersist,
} from '../shared/draggableButton.js';
import { decorateButton } from '../shared/buttonChrome.js';
import {
  coordKey,
  coordTypeKey,
  findRouteForBody,
  buildDeployUrl,
  buildCollectUrl,
  findNextMicroTarget,
  countRemainingMicroTargets,
} from './pure.js';
import {
  readCurrentBody,
  readDeployLegs,
  findNextCollectPlanetCp,
  isStep2,
  selectAllShips,
  clickContinue,
  loadAllResources,
  clickDispatch,
  waitForStep2,
} from './domHelpers.js';

// ─── DOM ids / storage keys ─────────────────────────────────────────────

const FS_UNIFIED_ID = 'oge-fs-unified';
const FS_MICRO_ZONE_ID = 'oge-fs-micro-zone';
const FS_COLLECT_ZONE_ID = 'oge-fs-collect-zone';

const FS_POS_KEY = 'oge_fsUnifiedPos';
const FOCUS_KEY = 'oge_focusedBtn';

const DRAG_THRESHOLD = 8;
const DEFAULT_EDGE_OFFSET_PX = 20;
const FLASH_MS = 1500;
const SENT_LOCK_MS = 3000;
const LONG_PRESS_MS = 300;

// Colours — distinct from sendExp (blue) / sendCol (green/teal).
const BG_MICRO = 'rgba(123,63,160,0.7)'; // violet, semi-transparent
const BG_COLLECT = 'rgba(31,111,111,0.7)'; // teal-dark, semi-transparent

// ─── helpers (impure env reads) ─────────────────────────────────────────

const gameBase = () => location.href.split('?')[0];
const onFleetdispatch = () => location.search.includes('component=fleetdispatch');
const urlHasAm = () => /[?&]am\d+=/.test(location.search);
/** @param {string} name */
const urlParam = (name) => new URLSearchParams(location.search).get(name);
// True only when the URL was generated by clicking Send All — has coords + no
// micro-fleet preload. Excludes bare manual ?component=fleetdispatch navigation.
const urlHasCollect = () => onFleetdispatch() && !urlHasAm() && urlParam('galaxy') !== null;
/** Builds "to G:S:P 🌙/🪐" from current URL params; empty string when absent. */
const urlCoordsLabel = () => {
  const g = urlParam('galaxy'), s = urlParam('system'), p = urlParam('position');
  if (!g || !s || !p) return '';
  return `to ${g}:${s}:${p} ${urlParam('type') === '3' ? '🌙' : '🪐'}`;
};

/**
 * URL of the OG-E Dashboard extension page, resolved once via
 * `browser/chrome.runtime.getURL`. Empty string when the WebExtension
 * runtime API isn't present (test environments) — {@link openDashboardRoutes}
 * guards on this. Mirrors the resolver in `settingsUi/sections/data.js`
 * (kept local — a feature must not import another feature).
 *
 * @type {string}
 */
const DASHBOARD_URL = (() => {
  try {
    const g = /** @type {any} */ (/** @type {unknown} */ (globalThis));
    const ns = g.browser ?? g.chrome;
    const url = ns?.runtime?.getURL?.('dashboard.html');
    return typeof url === 'string' ? url : '';
  } catch {
    return '';
  }
})();

/**
 * Open the Dashboard's Daily Resource Run tab in a new tab, pre-selecting the
 * current universe (`?host=`) and deep-linking the routes tab (`?tab=routes`).
 * No-op (returns false) when the runtime URL is unavailable, so the caller
 * can fall back to an in-place hint.
 *
 * @returns {boolean} Whether the dashboard was opened.
 */
const openDashboardRoutes = () => {
  if (!DASHBOARD_URL) return false;
  const universeId = parseUniverseId(location.host);
  const url =
    DASHBOARD_URL +
    (universeId ? `?host=${encodeURIComponent(universeId)}&tab=routes` : '?tab=routes');
  window.open(url, '_blank');
  return true;
};

/**
 * Set of {@link coordTypeKey}s that currently have a deployment inbound —
 * the "already sent a micro-fleet here" guard.
 *
 * @returns {Set<string>}
 */
const microInFlightKeys = () => {
  const set = new Set();
  for (const leg of readDeployLegs()) set.add(coordTypeKey(leg.dest));
  return set;
};

/**
 * Set of {@link coordKey}s of planets that already have a deployment
 * inbound to `target` — the "already collected" guard for the next-planet
 * walk.
 *
 * @param {import('../../state/fsRoutes.js').TargetCoord | null} target
 * @returns {Set<string>}
 */
const collectedOriginKeys = (target) => {
  const set = new Set();
  if (!target) return set;
  const tkt = coordTypeKey(target);
  for (const leg of readDeployLegs()) {
    if (leg.origin && coordTypeKey(leg.dest) === tkt) {
      set.add(coordKey(leg.origin));
    }
  }
  return set;
};

// ─── label painting ─────────────────────────────────────────────────────

/**
 * Paint a zone with up to three lines: main text, optional subtitle below,
 * optional micro-hint at the bottom (dimmer and smaller).
 *
 * @param {HTMLElement | null} el
 * @param {string} big
 * @param {string} [small]   subtitle below main (0.44em, 85% opacity)
 * @param {string} [hint]    micro-hint at bottom (0.37em, 55% opacity)
 * @returns {void}
 */
const setLabel = (el, big, small, hint) => {
  if (!el) return;
  el.textContent = '';
  const wrap = document.createElement('div');
  wrap.style.cssText =
    'display:flex;flex-direction:column;align-items:center;justify-content:center;line-height:1.1;width:100%;';
  const middle = document.createElement('div');
  middle.textContent = big;
  middle.style.cssText = 'font-size:0.88em;';
  wrap.appendChild(middle);
  if (small) {
    const sub = document.createElement('div');
    sub.textContent = small;
    sub.style.cssText = 'font-size:0.44em;opacity:0.85;letter-spacing:0.3px;margin-top:2px;';
    wrap.appendChild(sub);
  }
  if (hint) {
    const bot = document.createElement('div');
    bot.textContent = hint;
    bot.style.cssText = 'font-size:0.37em;opacity:0.55;margin-top:2px;letter-spacing:0.3px;';
    wrap.appendChild(bot);
  }
  el.appendChild(wrap);
};

/**
 * Flash a transient label on an element, then repaint via {@link refresh}.
 *
 * @param {HTMLElement | null} el
 * @param {string} text
 * @returns {void}
 */
const flash = (el, text) => {
  if (!el) return;
  setLabel(el, text);
  setTimeout(() => refresh(), FLASH_MS);
};

// ─── redirect handoff ───────────────────────────────────────────────────

/**
 * Stash the post-send redirect for a MICRO send: bare fleetdispatch on the
 * same body (so the next tap re-derives the next target from a refreshed
 * event ticker). Written synchronously, just before the dispatch click.
 *
 * @returns {void}
 */
const stashMicroRedirect = () => {
  const cp = urlParam('cp');
  const url =
    gameBase() + '?page=ingame&component=fleetdispatch' + (cp ? `&cp=${cp}` : '');
  safeWrite(url);
};

/**
 * Stash the post-send redirect for a COLLECT send: the next planet still
 * needing collection, already aimed at the collect target. No redirect
 * (clears the key) when nothing's left — the game's own redirect stands.
 *
 * @param {import('../../state/fsRoutes.js').TargetCoord | null} target
 * @returns {void}
 */
const stashCollectRedirect = (target) => {
  if (!target) return;
  const nextCp = findNextCollectPlanetCp(
    collectedOriginKeys(target),
    coordKey(target),
  );
  if (!nextCp) return;
  const url = buildCollectUrl(gameBase(), target) + `&cp=${nextCp}`;
  safeWrite(url);
};

/** @param {string} url */
const safeWrite = (url) => {
  try {
    localStorage.setItem(FS_REDIRECT_KEY, url);
  } catch {
    // Private mode / quota — the send still works, just no auto-redirect.
  }
};

// ─── click handlers ─────────────────────────────────────────────────────

/** @type {boolean} */
let busy = false;

/**
 * TOP zone (Send) click. Idle/elsewhere → navigate to the next target for the
 * current source's route. On fleetdispatch → two-tap drive (Send → Next).
 *
 * @returns {void}
 */
const onMicroClick = () => {
  if (busy) return;
  const microZone = document.getElementById(FS_MICRO_ZONE_ID);

  if (onFleetdispatch()) {
    if (isStep2()) {
      stashMicroRedirect();
      clickDispatch();
      setLabel(microZone, 'Sent');
      lockBriefly();
      return;
    }
    if (urlHasAm()) {
      // Step 1 with the micro-fleet preloaded → advance to step 2.
      clickContinue();
      setLabel(microZone, 'Wait…');
      busy = true;
      waitForStep2().then(() => {
        busy = false;
        refresh();
      });
      return;
    }
    // On fleetdispatch but nothing configured (e.g. after a bare redirect)
    // → fall through to navigate to the next target.
  }

  const body = readCurrentBody();
  const route = findRouteForBody(fsRoutesStore.get().routes, body);
  if (!route) {
    // No route for this body — guide the user straight to where routes are
    // set up rather than just flashing an error. Falls back to the flash
    // when the dashboard URL can't be resolved (e.g. tests).
    if (!openDashboardRoutes()) flash(microZone, 'No route');
    return;
  }
  const next = findNextMicroTarget(route.targets, microInFlightKeys());
  if (!next) {
    flash(microZone, 'All sent');
    return;
  }
  location.href = buildDeployUrl(gameBase(), next, route.microFleet);
};

/**
 * BOTTOM zone (Collect) click. Idle/elsewhere → navigate to the collect
 * target from the current planet. On fleetdispatch → two-tap drive,
 * selecting all ships (step 1) and all resources (step 2).
 *
 * @returns {void}
 */
const onCollectClick = () => {
  if (busy) return;
  const collectZone = document.getElementById(FS_COLLECT_ZONE_ID);
  const target = fsRoutesStore.get().collectTarget;

  if (urlHasCollect()) {
    if (isStep2()) {
      loadAllResources();
      stashCollectRedirect(target);
      clickDispatch();
      setLabel(collectZone, 'Sent');
      lockBriefly();
      return;
    }
    // Step 1: select all ships, then continue.
    selectAllShips();
    clickContinue();
    setLabel(collectZone, 'Wait…');
    busy = true;
    waitForStep2().then(() => {
      busy = false;
      refresh();
    });
    return;
  }

  if (!target) {
    flash(collectZone, 'No target');
    return;
  }
  location.href = buildCollectUrl(gameBase(), target);
};

/**
 * Collect-zone LONG-PRESS. Mark the body you're currently on as the ad-hoc
 * collect target and persist it immediately.
 *
 * @returns {void}
 */
const onSetTargetClick = () => {
  const collectZone = document.getElementById(FS_COLLECT_ZONE_ID);
  const body = readCurrentBody();
  if (!body) {
    flash(collectZone, '?');
    return;
  }
  fsRoutesStore.update((prev) => ({ ...prev, collectTarget: body }));
  // Persist now — the user may navigate away before the debounce fires.
  flushFsRoutesStore();
  // Stamp the cross-device sync clock so this collect-target change wins
  // the next whole-universe newest-wins merge.
  void stampFsRoutesChanged();
  refresh();
};

/** Briefly lock the buttons while a dispatch + reload settles. */
const lockBriefly = () => {
  busy = true;
  setTimeout(() => {
    busy = false;
    refresh();
  }, SENT_LOCK_MS);
};

// ─── refresh (repaint unified button) ───────────────────────────────────

/**
 * Recompute and repaint the unified button from current DOM + store state.
 *
 * @returns {void}
 */
const refresh = () => {
  const microZone = document.getElementById(FS_MICRO_ZONE_ID);
  const collectZone = document.getElementById(FS_COLLECT_ZONE_ID);

  // DISPATCH (top zone) label.
  if (microZone) {
    if (onFleetdispatch() && isStep2()) {
      setLabel(microZone, 'Send', urlCoordsLabel() || undefined, 'Send');
    } else if (onFleetdispatch() && urlHasAm()) {
      setLabel(microZone, 'Send', urlCoordsLabel() || undefined, 'Next');
    } else {
      const body = readCurrentBody();
      const allRoutes = fsRoutesStore.get().routes;
      const route = findRouteForBody(allRoutes, body);
      if (!route) {
        setLabel(microZone, 'SETUP', undefined, 'Collectors (no routes)');
      } else {
        setLabel(microZone, 'Dispatch', `Collectors (${allRoutes.length})`);
      }
    }
  }

  // Send All (bottom zone) label — TAP collects, LONG-PRESS sets the target.
  // Active collect states only when URL came from clicking Send All (has coords).
  if (collectZone) {
    if (urlHasCollect() && isStep2()) {
      setLabel(collectZone, 'Send All', urlCoordsLabel() || undefined, 'Send');
    } else if (urlHasCollect()) {
      setLabel(collectZone, 'Send All', urlCoordsLabel() || undefined, 'Next');
    } else {
      const t = fsRoutesStore.get().collectTarget;
      if (t) {
        const icon = t.type === 3 ? '🌙' : '🪐';
        setLabel(collectZone, 'Send All', `to ${t.galaxy}:${t.system}:${t.position} ${icon}`, '(Hold to change target)');
      } else {
        setLabel(collectZone, 'Send All', undefined, '(Hold to set target)');
      }
    }
  }
};

// ─── mount / dispose ────────────────────────────────────────────────────

/** @type {{ dispose: () => void } | null} */
let installed = null;

/** @param {number} size */
const zoneFontSize = (size) => Math.round(size * 0.14) + 'px';

/**
 * Style the unified two-zone circular button. The wrapper defines the outer
 * circle geometry; each zone (Send / Collect) is an equal-height flex child.
 *
 * @param {HTMLElement} wrap
 * @param {HTMLElement[]} zones  [microZone, collectZone]
 * @param {number} size
 * @param {string[]} bgs  one bg per zone
 * @returns {void}
 */
const styleZones = (wrap, zones, size, bgs) => {
  wrap.style.cssText = [
    'position:fixed',
    'border-radius:50%',
    'overflow:hidden',
    'display:flex',
    'flex-direction:column',
    'z-index:99999',
    'touch-action:none',
    'user-select:none',
    'cursor:pointer',
    'box-shadow:0 8px 22px rgba(0,0,0,0.55),0 3px 8px rgba(0,0,0,0.45),0 0 0 1px rgba(0,0,0,0.40)',
    `width:${size}px`,
    `height:${size}px`,
  ].join(';');
  zones.forEach((z, i) => {
    z.style.cssText = [
      'flex:1',
      'display:flex',
      'align-items:center',
      'justify-content:center',
      'text-align:center',
      'color:#fff',
      'font-weight:bold',
      'border:none',
      'cursor:pointer',
      `font-size:${zoneFontSize(size)}`,
      `background:${bgs[i]}`,
    ].join(';');
  });
};

/**
 * Restore a saved drag position onto `wrap`, else anchor bottom-right.
 *
 * @param {HTMLElement} wrap
 * @param {string} posKey
 * @param {number} size
 * @returns {void}
 */
const placeWrap = (wrap, posKey, size) => {
  const saved = safeJson(posKey);
  if (
    saved &&
    typeof saved === 'object' &&
    typeof (/** @type {any} */ (saved).x) === 'number' &&
    typeof (/** @type {any} */ (saved).y) === 'number'
  ) {
    const p = /** @type {{ x: number, y: number }} */ (saved);
    wrap.style.left = Math.min(p.x, window.innerWidth - size) + 'px';
    wrap.style.top = Math.min(p.y, window.innerHeight - size) + 'px';
  } else {
    wrap.style.right = DEFAULT_EDGE_OFFSET_PX + 'px';
    wrap.style.bottom = DEFAULT_EDGE_OFFSET_PX + 'px';
  }
};

/** @param {string} key */
const safeJson = (key) => {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
};

/**
 * Install the unified fleet-save button. Idempotent — a second call returns the
 * same dispose fn. Gated on `settings.fsCollectMode`; flipping it at
 * runtime mounts/removes the widget live.
 *
 * @returns {() => void} Dispose handle.
 */
export const installFsCollect = () => {
  if (installed) return installed.dispose;

  /** @type {ReturnType<import('../shared/draggableButton.js').installDrag> | null} */
  let dragHandle = null;
  /** @type {number | null} */
  let longPressTimer = null;
  /** Set true when a long-press fired, so the trailing click is swallowed. */
  let longPressFired = false;
  /** Pointer-down coords, to cancel the long-press once a drag starts. */
  let pressX = 0;
  let pressY = 0;

  // ── radial sweep (hold indicator on the collect zone) ──────────────────
  // The bottom zone is the bottom half of a circle. conic-gradient centered
  // at `50% 0%` (= button center = top of zone) sweeps from 90° (right) to
  // 270° (left) clockwise — exactly the visible 180° of the semicircle.
  /** @type {number | null} */
  let sweepRaf = null;
  /** @type {HTMLElement | null} */
  let sweepEl = null;

  /** @param {HTMLElement} zone */
  const startSweep = (zone) => {
    stopSweep();
    const el = document.createElement('div');
    el.style.cssText = 'position:absolute;inset:0;pointer-events:none;';
    zone.appendChild(el);
    sweepEl = el;
    const t0 = performance.now();
    const tick = () => {
      const pct = Math.min((performance.now() - t0) / LONG_PRESS_MS, 1);
      const deg = pct * 184; // slight overshoot so last frame is fully filled
      el.style.background =
        `conic-gradient(from 90deg at 50% 0%, rgba(255,255,255,0.18) ${deg}deg, transparent ${deg}deg)`;
      if (pct < 1) sweepRaf = requestAnimationFrame(tick);
    };
    sweepRaf = requestAnimationFrame(tick);
  };

  const stopSweep = () => {
    if (sweepRaf !== null) { cancelAnimationFrame(sweepRaf); sweepRaf = null; }
    sweepEl?.remove();
    sweepEl = null;
  };
  // ───────────────────────────────────────────────────────────────────────

  const clearLongPress = () => {
    if (longPressTimer !== null) {
      clearTimeout(longPressTimer);
      longPressTimer = null;
    }
    stopSweep();
  };

  const mount = () => {
    if (document.getElementById(FS_UNIFIED_ID)) {
      return;
    }
    const size = settingsStore.get().fsBtnSize;

    // Create wrapper and two zones.
    const wrap = document.createElement('div');
    wrap.id = FS_UNIFIED_ID;
    // Subtle hover title — the button's identity, hidden until hover.
    wrap.title = 'Daily Resource Run';

    const microZone = document.createElement('button');
    microZone.type = 'button';
    microZone.id = FS_MICRO_ZONE_ID;
    microZone.tabIndex = 0;
    microZone.setAttribute('aria-label', 'Send micro-fleets');

    const collectZone = document.createElement('button');
    collectZone.type = 'button';
    collectZone.id = FS_COLLECT_ZONE_ID;
    collectZone.tabIndex = 0;
    collectZone.setAttribute('aria-label', 'Tap to collect; long-press to set the collect target');

    styleZones(wrap, [microZone, collectZone], size, [BG_MICRO, BG_COLLECT]);
    wrap.appendChild(microZone);
    wrap.appendChild(collectZone);
    // Engraved title ring + per-zone tap ripple/press.
    decorateButton({
      host: wrap,
      zones: [microZone, collectZone],
      title: 'Daily Resource Run',
      ringId: 'oge-ring-fs',
    });
    placeWrap(wrap, FS_POS_KEY, size);
    document.body.appendChild(wrap);

    // Install drag on the outer wrapper.
    dragHandle = installDrag({ element: wrap, posKey: FS_POS_KEY, dragThreshold: DRAG_THRESHOLD });

    // Micro zone — regular click.
    microZone.addEventListener('click', (e) => {
      if (dragHandle?.wasDrag()) { dragHandle.resetDrag(); return; }
      e.stopPropagation();
      onMicroClick();
    });

    // Collect zone — TAP collects, LONG-PRESS sets the target. The long-press
    // timer is armed on pointerdown, disarmed on release/leave, and cancelled
    // once movement crosses the drag threshold (so dragging never sets the
    // target). A fired long-press sets `longPressFired` so the click handler
    // swallows the trailing tap.
    collectZone.addEventListener('pointerdown', (e) => {
      longPressFired = false;
      pressX = e.clientX;
      pressY = e.clientY;
      clearLongPress();
      startSweep(collectZone);
      longPressTimer = setTimeout(() => {
        longPressTimer = null;
        longPressFired = true;
        stopSweep();
        onSetTargetClick();
      }, LONG_PRESS_MS);
    });
    collectZone.addEventListener('pointermove', (e) => {
      if (
        longPressTimer !== null &&
        (Math.abs(e.clientX - pressX) > DRAG_THRESHOLD ||
          Math.abs(e.clientY - pressY) > DRAG_THRESHOLD)
      ) {
        clearLongPress();
      }
    });
    collectZone.addEventListener('pointerup', clearLongPress);
    collectZone.addEventListener('pointercancel', clearLongPress);
    collectZone.addEventListener('pointerleave', clearLongPress);
    // Long-press on touch can raise the native context menu — suppress it so
    // the gesture is ours alone.
    collectZone.addEventListener('contextmenu', (e) => e.preventDefault());
    collectZone.addEventListener('click', (e) => {
      if (dragHandle?.wasDrag()) { dragHandle.resetDrag(); return; }
      if (longPressFired) { longPressFired = false; return; }
      e.stopPropagation();
      onCollectClick();
    });

    installFocusPersist({ button: microZone, focusKey: FOCUS_KEY, focusValue: 'fs-unified-micro' });
    installFocusPersist({ button: collectZone, focusKey: FOCUS_KEY, focusValue: 'fs-unified-collect' });

    refresh();
  };

  const removeButton = () => {
    clearLongPress();
    document.getElementById(FS_UNIFIED_ID)?.remove();
  };

  /**
   * Live-resize the mounted button. Only width/height/font-size change —
   * NOT the full cssText — so a dragged position survives a size change.
   *
   * @param {number} size
   */
  const updateSize = (size) => {
    const wrap = document.getElementById(FS_UNIFIED_ID);
    if (wrap) {
      wrap.style.width = size + 'px';
      wrap.style.height = size + 'px';
    }
    const zoneIds = [FS_MICRO_ZONE_ID, FS_COLLECT_ZONE_ID];
    zoneIds.forEach((id) => {
      const z = document.getElementById(id);
      if (z) z.style.fontSize = zoneFontSize(size);
    });
    refresh();
  };

  const initial = settingsStore.get();
  if (initial.fsCollectMode) {
    if (document.body) mount();
    else document.addEventListener('DOMContentLoaded', () => {
      if (installed && settingsStore.get().fsCollectMode) mount();
    }, { once: true });
  }

  let prevMode = initial.fsCollectMode;
  let prevSize = initial.fsBtnSize;
  const unsubSettings = settingsStore.subscribe((next) => {
    if (next.fsCollectMode !== prevMode) {
      if (next.fsCollectMode) { if (document.body) mount(); }
      else removeButton();
      prevMode = next.fsCollectMode;
    }
    if (next.fsBtnSize !== prevSize) {
      updateSize(next.fsBtnSize);
      prevSize = next.fsBtnSize;
    }
  });

  const unsubRoutes = fsRoutesStore.subscribe(() => refresh());

  installed = {
    dispose: () => {
      removeButton();
      unsubSettings();
      unsubRoutes();
      installed = null;
    },
  };
  return installed.dispose;
};

/**
 * Test-only reset — runs dispose and clears the busy flag so each case
 * starts clean.
 *
 * @returns {void}
 */
export const _resetFsCollectForTest = () => {
  if (installed) {
    installed.dispose();
    installed = null;
  }
  busy = false;
};

// Re-export the pure pipeline pieces some tests import via the feature
// entry point (mirrors sendCol re-exporting derive/render).
export { refresh as _refreshForTest };
